### ISSUE TITLE
A JSONObject text must begin with '{'

### ISSUE THREAD

**Issue by xephon2** [oxygenxml/oxygen-resources-converter#29]
Hi,

the JSON to XML conversion did not work for me. The following error appears:

```
System-ID: C:\Users\Stefan.Eike\DITA\de-DE\monitoring\strings\strings.json
Fehlerlevel: error
Beschreibung: A JSONObject text must begin with '{'
```

Anonymized file: [strings.zip](https://github.com/oxygenxml/oxygen-resources-converter/files/1719411/strings.zip)

**Note:** The anonymized file has duplicate key errors, which happens because of the anonymization. This does not happen in the original file. oXygen XML does not show any structural issues there (green light).

**Comment by raducoravu** [comment]
I made changes to your samples so that the keys are not duplicate (because the duplicate keys were hiding all other problems. I'm attaching the modified sample.

[strings_fixed.zip](https://github.com/oxygenxml/oxygen-resources-converter/files/1722946/strings_fixed.zip)

Unfortunately I cannot reproduce the problem using the latest plugin and my fixed sample JSON.

**Comment by xephon2** [comment]
Hi @raducoravu, I can reproduce the error with your fixed file.

Software used:

* <oXygen/> XML Editor 19.1, build 2017121318
* Batch Converter 1.1.1

**Comment by raducoravu** [comment]
@xephon2 Sorry, my bad, initially I tested our default JSON to XML conversion actions bundled with Oxygen instead of the plugin's ones.
We'll look into this.

**Comment by DunaMariusCosmin** [comment]
The new release (1.1.2) contains this fix. 
Thanks you for this report.
